_svc_ayuda() {
  echo ""
  echo "  svc — Docker Service Manager"
  echo ""
  echo "  Uso: svc <comando> [<servicio>] [argumentos]"
  echo ""
  echo "  -- Comandos globales (sin servicio) ────────────────────────"
  echo "    lista               Lista servicios con estado"
  echo "    health              Dashboard de salud (health, uptime, restarts)"
  echo "    update-all [-y]     Actualizar todos los servicios"
  echo "    port-map            Mapa global de puertos (detecta conflictos)"
  echo "    size                Consumo de disco por servicio"
  echo "    net                 Mapa de redes Docker"
  echo "    watch [N]           Monitoreo continuo (refresh cada N seg)"
  echo "    create <nombre>     Scaffolding de nuevo servicio"
  echo "    capabilities [q]    Descubrir capacidades y comandos disponibles"
  echo "    lobehub <acción>    Preflight, verify, Redis/DB y recuperación segura"
  echo "    menu                Menu TUI interactivo con fzf"
  echo ""
  echo "  -- Comandos propios (requieren servicio) ───────────────────"
  echo "    update <svc>        Pull + recrear contenedores"
  echo "    backup <svc>        Backup volumenes + bind mounts"
  echo "    restore <svc> [f]   Restaurar desde backup"
  echo "    depends <svc>       Ver servicios y depends_on"
  echo "    env <svc> [edit]    Ver/editar variables de entorno"
  echo "    open <svc>          Mostrar URL + QR + clipboard"
  echo ""
  echo "  -- Docker Compose (passthrough) ────────────────────────────"
  echo "    up <svc>            Crear e iniciar contenedores"
  echo "    down <svc>          Detener y eliminar contenedores"
  echo "    restart <svc>       Reiniciar servicio"
  echo "    start <svc>         Iniciar servicio detenido"
  echo "    stop <svc>          Detener servicio"
  echo "    kill <svc>          Forzar parada"
  echo "    pause <svc>         Pausar servicio"
  echo "    unpause <svc>       Reanudar servicio pausado"
  echo "    logs <svc>          Ver logs en vivo (ultimas 200 lineas)"
  echo "    ps <svc>            Listar contenedores"
  echo "    stats <svc>         Uso de CPU/RAM en tiempo real"
  echo "    top <svc>           Procesos corriendo"
  echo "    exec <svc> <cmd>    Ejecutar comando en contenedor"
  echo "    build <svc>         Construir/reconstruir imagen"
  echo "    pull <svc>          Descargar imagen"
  echo "    images <svc>        Listar imagenes"
  echo "    rm <svc>            Eliminar contenedores detenidos"
  echo "    config <svc>        Ver configuracion resuelta"
  echo "    cp <svc> src dst    Copiar archivos"
  echo "    events <svc>        Eventos en tiempo real"
  echo "    port <svc> <port>   Ver puerto publico"
  echo "    volumes <svc>       Listar volumenes"
  echo "    scale <svc> s=N     Escalar servicio"
  echo "    run <svc> <cmd>     Ejecutar comando one-off"
  echo "    wait <svc>          Esperar a que paren los contenedores"
  echo ""
  echo "  -- Notas ───────────────────────────────────────────────────"
  echo "    Cualquier comando de 'docker compose' funciona como"
  echo "    passthrough sin modificar el codigo."
  echo ""
  echo "    Backups se rotan automaticamente (default: ultimos 5)."
  echo "    Configurable con BACKUP_KEEP=N"
  echo ""
}
