# Homepage — Widgets globales (barra superior)
# Docs: https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    label: NAS

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
